### PR TITLE
add latex and css

### PR DESCRIPTION
**Pull request by EddieTheEd**
pretty self explanatory it adds latex and css to your default page. I'm not quite sure how jekyll works, **so** if this doesn't work, change your metadata!**

Here's an example of the change you would need to make:

**Initial**
```
---
title: blah blah
---
``` 

**final**
```
---
title: blah blah
layout: default
---
```

I've also added an assets folder + a css folder, which is by default linked in the head. You can change the css as you see fit.

With love,
Ed

### CODE REVIEW

**Comment by EddieTheEd** [comment]
hello

**Comment by spicata** [comment]
I am about 70% this CSS fix won't work because Github Pages.

**Comment by EddieTheEd** [comment]
huh i took the css from ur repo

odd

**Comment by spicata** [comment]
You need a _layouts folder with your own layout in it, which means you have to not use the Github pages template, which means you have to write everything on your own.

**Comment by EddieTheEd** [comment]
I realise that now

Goofy ahh github pages I'll fix it later

**Pull request merged**
